### ISSUE TITLE
Обновление до версии 1.3.*

### ISSUE THREAD

**Issue by gruzzilkin** [enb-bem/enb-bemxjst#18]
Привет!
У меня возникли непонятные проблемы с обновлением с `1.2.0` до `1.3.1`.
 
Сначала было куча ошибок, связанных с синтаксисом `bemhtml`, который раньше допускал конструкции вида 
```js
attrs()(this.ctx.attrs)
```
После исправления всех ошибок, сборка работает отлично, но непонятным образом ломается работа `tag()()`. Причины отловить пока что не смог.

**При этом с флагом `devMode: true` тэги обрабатываются корректно.**

Это баг, фича, или просто я что-то делаю не так? Если нет готового рецепта, я попробую локализовать проблему и сделать небольшой пример.

**Comment by zxqfox** [comment]
Актуально?

**Comment by gruzzilkin** [comment]
Я  сижу на 1.2, но в планах перейти на bh, поэтому не актуально, наверное 😃

**Comment by zxqfox** [comment]
Ну если там действительно есть баг, то хорошо бы его поймать, конечно.

@tadatuta ты знаешь что делать ;-)

**Comment by blond** [comment]
Воспроизвести не смог, закрываю.

@gruzzilkin если обнаружишь переоткрой ;)
