### ISSUE TITLE
Get rid of bemhtml-old

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bemxjst#25]
Now the only difference between `bemhtml` and `bemhtml-old` techs is the use of `bemhtml-compat`.

I suggest to run `bemhtml-compat` in `bemhtml` tech as optional step switched on by default so there won't be any reason to have 2 different techs any more.

// @arikon

**Comment by blond** [comment]
Which option to use to disable `bemhtml-compat`? `compat: false`?
