### ISSUE TITLE
Throw error if there is no base templates

### ISSUE THREAD

**Issue by blond** [enb-bem/enb-bemxjst#60]
If you do not add base teamples — assembly will be successful, but if you call `BEMHTML.apply(bemjson)` you will see strange error:

```
Error: Match failed.
```

**Comment by tormozz48** [comment]
@blond What you mean by base templates?
How it correlates with bemtree and bemhtml mocks which are used if surce files are not exists?

**Comment by tormozz48** [comment]
@blond 

И все-таки нужно решить что делать по этой задаче.
Насколько я помню наше с тобой обсуждение ничем не закончилось

**Comment by tadatuta** [comment]
@veged рекомендовал добавить вот такую проверку
```
oninit(function(exports, context) {
  if(!context.BEMContext) throw Error('Seems like you have no base templates from i-bem.bemhtml');
})
```

**Comment by blond** [comment]
@tadatuta такая проверка выдаст ошибку во время выполнения, а не во время сборки.

**Comment by tadatuta** [comment]
Кажется, что с этим уже вполне можно жить.
Но если у вас есть более годный способ — я только за.

**Comment by blond** [comment]
@tadatuta, можно анализировать каждый файл на наличие `oninit(function(exports, context) {` и внутри `BEMContext`. Или такой анализ лучше делать где-то в `bemhint`?

**Comment by tormozz48** [comment]
Анализировать каким способом? 
Если просто текстовый код регулярными выражениями, то кажется, что опасно, так как код шаблонов в принципе может быть абсолютно произвольным

**Comment by tavriaforever** [comment]
Кажется, вариант @veged пока самый годный

**Comment by tormozz48** [comment]
Пока удалось реализовать проверку и вывод ошибки только для production режима.
Завел [связанную задачу в bem-xjst](https://github.com/bem/bem-xjst/issues/68)

Готовый код по данной задаче находится в ветке issue-60
