### ISSUE TITLE
Add {bemhtml,bemtree}.js to default sourceSuffixes to corresponding techs

### ISSUE THREAD

**Issue by tadatuta** [enb-bem/enb-bemxjst#72]

**Comment by blond** [comment]
It has been done in `master` branch: [BEMHTML](https://github.com/enb-bem/enb-bemxjst/blob/master/techs/bemhtml.js#L40), [BEMTREE](https://github.com/enb-bem/enb-bemxjst/blob/master/techs/bemtree.js#L36).
