### ISSUE TITLE
Provide an option to set required libs as globals for templates

### ISSUE THREAD

**Issue by apsavin** [enb-bem/enb-bemxjst#97]
As discussed at https://github.com/bem/bem-xjst/issues/41
I have some libs as ym modules and want them to be global for templates.

**Comment by apsavin** [comment]
Can you provide it? Wanna a PR?

**Comment by apsavin** [comment]
Well, I decided to don't use globals even in templates. Thanks)

**Comment by blond** [comment]
:tada: :grinning:
